// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Brandheader: typeof import('./src/components/base/BrandHeader/Brandheader.vue')['default']
    ChangelogEntry: typeof import('./src/components/feature/ChangelogEntry/ChangelogEntry.vue')['default']
    CloseScreenButton: typeof import('./src/components/base/CloseScreenButton/CloseScreenButton.vue')['default']
    ScreenAdvisor: typeof import('./src/components/feature/ScreenAdvisor/ScreenAdvisor.vue')['default']
    ScreenChangelog: typeof import('./src/components/feature/ScreenChangelog/ScreenChangelog.vue')['default']
    ScreenContent: typeof import('./src/components/feature/ScreenContent/ScreenContent.vue')['default']
    ScreenMarketing: typeof import('./src/components/feature/ScreenMarketing/ScreenMarketing.vue')['default']
    'TSXContentScreen.ce': typeof import('./src/components/feature/TSXContentScreen/TSXContentScreen.ce.vue')['default']
    TSXContentScreenContent: typeof import('./src/components/feature/TSXContentScreen/TSXContentScreenContent.vue')['default']
    'TSXContentScreenTrigger.ce': typeof import('./src/components/feature/TSXContentScreenTrigger/TSXContentScreenTrigger.ce.vue')['default']
  }
}
